version: '3.5'
services:
  presto:
    ports:
      - "8080:8080"
    image: prestosql/presto:329
    volumes:
      - ./docker/presto/etc/catalog/memory.properties:/usr/lib/presto/etc/catalog/memory.properties:ro
      - ./docker/presto/etc/config.properties:/usr/lib/presto/etc/config.properties:ro
      - ./docker/presto/etc/jvm.config:/usr/lib/presto/etc/jvm.config:ro
      - ./docker/presto/etc/node.properties:/usr/lib/presto/etc/node.properties:ro

networks:
  default:
    external:
      name: dbt-net
