version: 2.1

jobs:
  unit:
    docker:
      - image: fishtownanalytics/test-container:6
        environment:
          DBT_INVOCATION_ENV: circle
    steps:
      - checkout
      - run: tox -e flake8,unit

  integration:
    docker:
      - image: fishtownanalytics/test-container:6
        environment:
          DBT_INVOCATION_ENV: circle

      - image: fishtownanalytics/presto:1
        name: presto
    steps:
      - checkout
      - run:
          name: Wait for Presto
          command: dockerize -wait tcp://presto:8080 -timeout 5m -wait-retry-interval 5s
      - run:
          name: Checkout test project
          command: git clone --branch presto-support https://github.com/fishtown-analytics/dbt-integration-tests.git
      - run:
          name: Run integration tests
          command: tox -e integration-presto
          no_output_timeout: 1h
          environment:
              DBT_PROFILES_DIR: /home/dbt_test_user/project/docker/dbt/
      - store_artifacts:
          path: ./logs

workflows:
  version: 2
  test-everything:
    jobs:
      - unit
      - integration:
          requires:
            - unit
